// This file is generated by Slice Machine. Update with care!

import ClassTextContentSlice from './ClassTextContentSlice';

export {
	ClassTextContentSlice,
};

export const components = {
	class_text_content_slice: ClassTextContentSlice,
};
