# This is a basic workflow to help you get started with Actions

name: Reset users hearts

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/5 * * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cron:
    runs-on: ubuntu-latest
    
    steps:
      - name: Reset users hearts every 24 hours
        run: |
          curl --request GET \
          --url 'http://localhost:3000/api/jobs/reset-users-hearts'
